version: "3.4"
services:
  docker:
    container_name: flask-app
    build: ./dockerfile
    ports:
      - "5000:5000"
    restart:
      always

  nginx:
    image: nginx:latest
    container_name: proxy-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    restart:
      always